src/Entity/Category.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    // #[Assert\Regex(pattern: '/^[a-zA-Z- ]*$/', message: 'Le nom de catégorie ne doit pas contenir d\'accents')]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    private $slug;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'string', length: 255)]
    private $img;

    #[ORM\OneToMany(mappedBy: 'category_id', targetEntity: Product::class)]
    private $product;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'categories')]
    private $parentCategory;

    #[ORM\OneToMany(mappedBy: 'parentCategory', targetEntity: self::class)]
    private $categories;

    public function __construct()
    {
        $this->product = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): self
    {
        $this->img = $img;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProduct(): Collection
    {
        return $this->product;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->product->contains($product)) {
            $this->product[] = $product;
            $product->setCategoryId($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->product->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCategoryId() === $this) {
                $product->setCategoryId(null);
            }
        }

        return $this;
    }

    public function getParentCategory(): ?self
    {
        return $this->parentCategory;
    }

    public function setParentCategory(?self $parentCategory): self
    {
        $this->parentCategory = $parentCategory;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(self $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->setParentCategory($this);
        }

        return $this;
    }

    public function removeCategory(self $category): self
    {
        if ($this->categories->removeElement($category)) {
            // set the owning side to null (unless already changed)
            if ($category->getParentCategory() === $this) {
                $category->setParentCategory(null);
            }
        }

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $product_name;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'string', length: 120)]
    private $img;

    #[ORM\Column(type: 'float')]
    private $price;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'product')]
    #[ORM\JoinColumn(nullable: false)]
    private $category_id;

    #[ORM\Column(type: 'string', length: 30, nullable: true)]
    private $img2;

    #[ORM\Column(type: 'datetime_immutable')]
    private $PublishedAt;

    #[ORM\Column(type: 'string', length: 255)]
    private $statutes;

    #[ORM\Column(type: 'string', length: 4000)]
    private $ingredients;

    #[ORM\Column(type: 'integer')]
    private $weight;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductName(): ?string
    {
        return $this->product_name;
    }

    public function setProductName(string $product_name): self
    {
        $this->product_name = $product_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCategoryId(): ?Category
    {
        return $this->category_id;
    }

    public function setCategoryId(?Category $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function getImg2(): ?string
    {
        return $this->img2;
    }

    public function setImg2(string $img2): self
    {
        $this->img2 = $img2;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeImmutable
    {
        return $this->PublishedAt;
    }

    public function setPublishedAt(\DateTimeImmutable $PublishedAt): self
    {
        $this->PublishedAt = $PublishedAt;

        return $this;
    }

    public function getStatutes(): ?string
    {
        return $this->statutes;
    }

    public function setStatutes(string $statutes): self
    {
        $this->statutes = $statutes;

        return $this;
    }

    public function getIngredients(): ?string
    {
        return $this->ingredients;
    }

    public function setIngredients(string $ingredients): self
    {
        $this->ingredients = $ingredients;

        return $this;
    }

    public function getWeight(): ?int
    {
        return $this->weight;
    }

    public function setWeight(int $weight): self
    {
        $this->weight = $weight;

        return $this;
    }
}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Validator\Constraints\Image;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'required' => true,
                'label' => 'Nom catégorie',
                'attr' => [
                    'maxLength' => 255,
                    'placeholder' => 'Exemple: L\'Amoureux Noir'
                ]
            ])

            ->add('description', TextareaType::class, [
                'required' => true,
                'label' => 'Description produit',
                'attr' => [
                    'maxLength' => 80000,
                    'placeholder' => 'Exemple: Voici le nouveau venu dans la famille des ganaches.... '
                ]
            ])

            ->add('img', FileType::class, [
                'required' => false,
                'label' => 'Image produit',
                'mapped' => false,
                'help' => 'jpeg, png, gif, svg, eps, psd, tiff, jp2 ou webp - 8 Mo maximum ',
                'constraints' => [
                    new Image([
                        'maxSize' => '8M',
                        'maxSizeMessage' => 'Votre fichier est trop volumineux ({{ size }} Mo). Taille maximum autorisée.',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                            'image/gif',
                            'image/svg',
                            'image/eps',
                            'image/psd',
                            'image/tiff',
                            'image/jp2',
                            'image/webp',
                        ],
                        'mimeTypesMessage' => 'Merci d\'utiliser un des formats suivant jpeg, png, gif, svg, eps, psd, tiff, jp2 ou webp. '
                    ])
                ]
            ])

            ->add('parentCategory', EntityType::class, [
                'required' => true,
                'label' => 'Catégorie',
                'class' => Category::class,
                'choice_label' => 'name'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;
use App\Repository\ProductRepository;
use CodeInc\StripAccents\StripAccents;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CategoryController extends AbstractController
{
    #[Route('/admin/category', name: 'category_admin_index')]
    public function index(CategoryRepository $categoryRepository): Response
    {
        $categories = $categoryRepository->findAll();
        return $this->render('admin/adminCategoryIndex.html.twig', [
            'categories' => $categories,
        ]);
    }

    #[Route('/categories', name: 'category_index')]
    public function categories(CategoryRepository $categoryRepository): Response
    {
        $categories = $categoryRepository->findBy(['parentCategory' => 2], ['name' => 'ASC']);
        return $this->render('category/index.html.twig', [
            'categories' => $categories
        ]);
    }

    #[Route('/categorie/{slug}', name: 'product_category')]
    public function category($slug, CategoryRepository $categoryRepository, ProductRepository $productRepository): Response
    {
        // récupérer les sous-catégories
        $category = $categoryRepository->findOneBy(['slug' => $slug]); // récupère l'id de la catégorie parente
        $sousCategories = $categoryRepository->findBy(['parentCategory' => $category->getId()]); // récupère les sous-catégories (catégories enfant)

        if (!empty($sousCategories)) {
            return $this->render('category/category.html.twig', [
                'category' => $category,
                'sousCategories' => $sousCategories
            ]);
        } else {
            $products = $productRepository->findBy(['category_id' => $category->getId()], ['product_name' => 'ASC']);
        }

        return $this->render('category/category.html.twig', [
            'category' => $category,
            'message' => 'aller récupérer les produits',
            'products' => $products
        ]);
    }

    #[Route('/admin/category/new', name: 'category_create')]
    public function create(Request $request, ManagerRegistry $managerRegistry): Response
    {
        $category = new Category(); //create new category
        $form = $this->createForm(CategoryType::class, $category); //create the form with the parameter of new Category
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            // $slugMinuscules = strtolower($form['name']->getData());
            // $slugSansCaracteresSpeciaux = str_replace([' ', '\'', '"', '&'], ['-', '-', '-', 'et'], $slugMinuscules);
            // $slugSansAccents = StripAccents::strip($slugSansCaracteresSpeciaux);
            // $category->setSlug($slugSansAccents);
            $slug = StripAccents::strip(str_replace([' ', '\'', '"', '&'], ['-', '-', '-', 'et'], strtolower($form['name']->getData())));
            $category->setSlug($slug);
            // throw new \Exception('À finir : remplacer les caractères avec accent dans le slug par des lettres sans accent');

            $cateImg = $form['img']->getData();
            $extensionImg = $cateImg->guessExtension();
            $nameImg = time() . '.' . $extensionImg;

            $cateImg->move($this->getParameter('dossier_photos_category'), $nameImg);
            $category->setImg($nameImg);

            $manager = $managerRegistry->getManager();
            $manager->persist($category);
            $manager->flush();
            $this->addFlash('success', 'La catégorie a bien été ajoutée.');
            return $this->redirectToRoute('category_admin_index');
        }
        return $this->render('admin/adminCategoryForm.html.twig', [
            'categoryForm' => $form->createView()
        ]);
    }

    #[Route('/admin/category/update/{id}', name: 'category_update')]
    public function update(CategoryRepository $categoryRepository, int $id, Request $request, ManagerRegistry $managerRegistry)
    {
        $category = $categoryRepository->find($id);
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $slug = StripAccents::strip(str_replace([' ', '\'', '"', '&'], ['-', '-', '-', 'et'], strtolower($form['name']->getData())));
            $category->setSlug($slug);
            $cateImg = $form['img']->getData();
            $nameOldImg = $category->getImg();
            if ($cateImg !== null) {
                $pathOldimg = $this->getParameter('dossier_photos_category') . '/' .
                    $nameOldImg;
                if (file_exists($pathOldimg)) {
                    unlink($pathOldimg);
                }
                $extensionImg = $cateImg->guessExtension();
                $nameImg = time() . '.' . $extensionImg;
                $cateImg->move($this->getParameter('dossier_photos_category'), $nameImg);
                $category->setImg($nameImg);
            } else {
                $category->setImg($nameOldImg);
            }

            $manager = $managerRegistry->getManager();
            $manager->persist($category);
            $manager->flush();
            $this->addFlash('success', 'La catégorie a bien été modifiée.');
            return $this->redirectToRoute('category_admin_index');
        }

        return $this->render('admin/adminCategoryForm.html.twig', [
            'categoryForm' => $form->createView()
        ]);
    }

    #[Route('/admin/category/delete/{id}', name: 'category_delete')]
    public function delete(CategoryRepository $categoryRepository, int $id, ManagerRegistry $managerRegistry)
    {
        $category = $categoryRepository->find($id);
        $nameImg = $category->getImg();
        if ($nameImg !== null) {
            $pathImg = $this->getParameter('dossier_photos_category') . '/' . $nameImg;
            if (file_exists($pathImg)) {
                unlink($pathImg);
            }
        }

        $manager = $managerRegistry->getManager();
        $manager->remove($category);
        $manager->flush();
        $this->addFlash('success', 'La catégorie a bien été supprimée.');
        return $this->redirectToRoute('category_admin_index');
    }
}

templates/category/adminIndex.html.twig
{# c'est la page liste des caté!! #}
{% extends 'adminBase.html.twig' %}

{% block title %}Category{% endblock %}

{% block body %}

<h2>Liste des catégories</h2>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Titre</th>
            <th scope="col">Description</th>
            <th scope="col">Catégorie</th>
            <th scope="col">cat. parent</th>
            <th scope="col">Image</th>
        </tr>
    </thead>
    <tbody>
        {% for category in categories %}
        <tr>
            <td class="align middle">{{ category.id }}</td>
            <td class="align middle">{{ category.name }}</td>
            <td class="align middle">{{ category.description }}</td>
            <td class="align middle">{{ category.name }}</td>
            <td class="align middle">{{ category.parentCategory ? category.parentCategory.name : '-' }}</td>
            <td class="align middle"><img src="{{ asset('img/category/' ~ category.img) }}" alt="{{ category.name }}">
            </td>
            <td class="align middle">
                <a href="{{ path('category_update', {'id': category.id}) }}" class="text-primary">
                    <i class="fas fa-pen-square"></i>
                </a>
                <a href="{{ path('category_delete', {'id': category.id}) }}" class="text-danger">
                    <i class="fas fa-trash-alt"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="d-flex justify-content-end my-5">
    <a href="{{ path('category_create')}}" class="btn btn-success">Ajouter une catégorie</a>
</div>

{% endblock %}

templates/category/category.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ category.name }} ♥ Les Amoureux du Chocolat ♥{% endblock %}

{% block body %}
<h1 class="text-center pt-3 mx-auto" id="category-title-h1">{{ category.name }}</h1>
<p class="section-title-p mb-5">Découvrez tous nos produits faits artisanalement.
    Un concentré d'amour, de passion et de création qui vont éveiller vos sens et vos papilles
    Laissez vous tentez par nos mélanges chocolat & fruits secs à la fois tendre et croquant.
</p>
<div class="row mx-auto">
    {% for product in products %}
    <div class="col-md-3 p-3 col-6 mx-auto" id="img-category-width">
        <div class="card border-0 card-product">
            <img src="{{ asset('img/Product/' ~ product.img ) }}" alt="photo principale" class="img-fluid">
            <div class="card-body  text-center">
                <h4 class="card-title" id="category-h4">{{ product.productName }}</h4>
                <a href=" {{ path('product_view', {'id':product.id})}} " class="btn intro-btn mb-5 mt-4"
                    id="btn-intro-category">Détails</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% include "shared/_scrolltop.html.twig" %}
{% endblock %}

templates/category/categoryForm.html.twig
{# la page ajout de catégorie #}
{% extends 'adminBase.html.twig' %}

{% block title %}Categorie{% endblock %}

{% block body %}


{{ form_start(categoryForm) }}
<div class="container">

	<div class="row">
		<div class="col-8">
			{{ form_row(categoryForm.name, {'label': 'Titre'}) }}
		</div>
		<div class="col-4">
			{{ form_row(categoryForm.parentCategory, {'label': 'Categorie'})}}
		</div>
	</div>

	<div class="col-12">
		{{ form_row(categoryForm.description, {'label': 'Description'}) }}
	</div>


	<div class="row">
		<div class="col-6">
			{{ form_row(categoryForm.img, {'label': 'image'}) }}
		</div>
	</div>

	<div class="col-12 d-flex justify-content-end">
		<a href="{{ path('category_admin_index') }}" class="btn btn-danger m-3">Annuler</a>
		<button class="btn btn-success m-3">Créer</button>
	</div>
</div>

{{ form_end(categoryForm) }}

{% endblock %}

templates/category/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catégories ♥ Les Amoureux du Chocolat ♥ {% endblock %}

{% block body %}

<main class="container-fluid">
    <h1 class="text-center mt-5 pt-5">Gammes De Produits </h1>
    <p class="text-center mt-4 category-view">Découvrez tous nos produits faits artisanalement.
        Un concentré d'amour, de passion et de création qui vont éveiller vos sens et vos papilles
    </p>
    <div class="row" id="category-display-product">
        {% for category in categories %}
        <div class="col-4 p-3" id="category-inline">
            <div class="card card-category border-0">
                <img src=" {{asset('img/category/' ~ category.img )}} " alt="photo principale {{category.name}}"
                    class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title text-center"><a href="{{ path('product_category', {'slug': category.slug}) }}"
                            class="text-center">{{
                            category.name }}</a> </h5>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% endblock %}