src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'string', length: 120)]
    private $slug;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'datetime')]
    private $created_at;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $updated_at;

    #[ORM\Column(type: 'string', length: 255)]
    private $featured_img;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private $user_id;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'category')]
    #[ORM\JoinColumn(nullable: false)]
    private $category_id;

    #[ORM\OneToMany(mappedBy: 'articles_id', targetEntity: Comment::class)]
    private $comment;

    #[ORM\Column(type: 'string', length: 100)]
    private $event;

    public function __construct()
    {
        $this->comment = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getFeaturedImg(): ?string
    {
        return $this->featured_img;
    }

    public function setFeaturedImg(string $featured_img): self
    {
        $this->featured_img = $featured_img;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getCategoryId(): ?category
    {
        return $this->category_id;
    }

    public function setCategoryId(?category $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComment(): Collection
    {
        return $this->comment;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comment->contains($comment)) {
            $this->comment[] = $comment;
            $comment->setArticlesId($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comment->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticlesId() === $this) {
                $comment->setArticlesId(null);
            }
        }

        return $this;
    }

    public function getEvent(): ?string
    {
        return $this->event;
    }

    public function setEvent(string $event): self
    {
        $this->event = $event;

        return $this;
    }
}

src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Boolean;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\ManyToOne(targetEntity: Article::class, inversedBy: 'comment')]
    #[ORM\JoinColumn(nullable: false)]
    private $articles_id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'user_id')]
    #[ORM\JoinColumn(nullable: false)]
    private $user_id;

    #[ORM\Column(type: 'boolean')]
    private $comment_status;

    #[ORM\Column(type: 'datetime')]
    private $created_at;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\OneToOne(mappedBy: 'fk_comment_id', targetEntity: Reponse::class, cascade: ['persist', 'remove'])]
    private $reponse;



    public function __construct()
    {
        $this->reponses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getArticlesId(): ?Article
    {
        return $this->articles_id;
    }

    public function setArticlesId(?Article $articles_id): self
    {
        $this->articles_id = $articles_id;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getCommentStatus(): ?Bool
    {
        return $this->comment_status;
    }

    public function setCommentStatus(Bool $comment_status): self
    {
        $this->comment_status = $comment_status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getReponse(): ?Reponse
    {
        return $this->reponse;
    }

    public function setReponse(?Reponse $reponse): self
    {
        // unset the owning side of the relation if necessary
        if ($reponse === null && $this->reponse !== null) {
            $this->reponse->setFkCommentId(null);
        }

        // set the owning side of the relation if necessary
        if ($reponse !== null && $reponse->getFkCommentId() !== $this) {
            $reponse->setFkCommentId($this);
        }

        $this->reponse = $reponse;

        return $this;
    }
}

src/Entity/Reponse.php
<?php

namespace App\Entity;

use App\Repository\ReponseRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReponseRepository::class)]
class Reponse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $answer;

    #[ORM\OneToOne(inversedBy: 'reponse', targetEntity: Comment::class, cascade: ['persist', 'remove'])]
    private $fk_comment_id;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAnswer(): ?string
    {
        return $this->answer;
    }

    public function setAnswer(string $answer): self
    {
        $this->answer = $answer;

        return $this;
    }

    public function getFkCommentId(): ?Comment
    {
        return $this->fk_comment_id;
    }

    public function setFkCommentId(?Comment $fk_comment_id): self
    {
        $this->fk_comment_id = $fk_comment_id;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Category;
use App\Repository\CategoryRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'required' => true,
                'label' => 'Nom de l\'article',
                'attr' => [
                    'maxLength' => 255,
                    'placeholder' => 'Exemple: La Saint Valentin'
                ]
            ])
            ->add('content', TextareaType::class, [
                'required' => true,
                'label' => 'Description article',
                'attr' => [
                    'maxLength' => 80000,
                    'placeholder' => 'Voici l\'évenment tant attendu cette année....'
                ]
            ])
            ->add('featured_img', FileType::class, [
                'required' => false,
                'label' => 'Image article',
                'mapped' => false,
                'help' => 'jpeg, png, gif, svg, eps, psd, tiff, jp2 ou webp - 8 Mo maximum ',
                'constraints' => [
                    new Image([
                        'maxSize' => '8M',
                        'maxSizeMessage' => 'Votre fichier est trop volumineux ({{ size }} Mo). Taille maximum autorisée.',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                            'image/gif',
                            'image/svg',
                            'image/eps',
                            'image/psd',
                            'image/tiff',
                            'image/jp2',
                            'image/webp',
                        ],
                        'mimeTypesMessage' => 'Merci d\'utiliser un des formats suivant jpeg, png, gif, svg, eps, psd, tiff, jp2 ou webp. '
                    ])
                ]
            ])
            ->add('category_id', EntityType::class, [
                'required' => true,
                'label' => 'Catégorie article',
                'class' => Category::class,
                'query_builder' => function (CategoryRepository $categoryRepository) {
                    return $categoryRepository->getBlogCategories();
                },
                'choice_label' => 'name'
            ])
            ->add('event', TextType::class, [
                'required' => true,
                'label' => 'Événement',
                'attr' => [
                    'maxLength' => 100,
                    'placeholder' => 'Veuillez décrire le type d\'événement'
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use App\Repository\CommentRepository;
use App\Repository\ReponseRepository;
use CodeInc\StripAccents\StripAccents;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ArticleController extends AbstractController
{
    #[Route('/admin/article', name: 'article_admin_index')]
    public function index(ArticleRepository $articleRepository): Response
    {
        $articles = $articleRepository->findAll();

        return $this->render('admin/adminArticleIndex.html.twig', [
            'articles' => $articles
        ]);
    }

    #[Route('/articles', name: 'article_index')]
    public function articles(ArticleRepository $articleRepository): Response
    {
        $articles = $articleRepository->findAll();

        return $this->render('article/index.html.twig', [
            'articles' => $articles
        ]);
    }

    #[Route('/article/{id}', name: 'article')]
    public function article(ArticleRepository $articleRepository, int $id, CommentRepository $commentRepository, ReponseRepository $reponseRepository): Response
    {
        $article = $articleRepository->find($id);
        $comments = $commentRepository->findBy(['articles_id' => $id]);
        $reponses = $reponseRepository->findAll();


        return $this->render('article/article.html.twig', [
            'article' => $article,
            'comments' => $comments,
            'reponses' => $reponses

        ]);
    }

    #[Route('/admin/article/new', name: 'article_create')]
    public function create(Request $request, ManagerRegistry $managerRegistry): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $slug = StripAccents::strip(str_replace([' ', '\'', '"', '&'], ['-', '-', '-', 'et'], strtolower($form['title']->getData())));
            $article->setSlug($slug);

            $artImg = $form['featured_img']->getData();
            $extensionImg = $artImg->guessExtension();
            $nameImg = time() . '.' . $extensionImg;

            $artImg->move($this->getParameter('dossier_photos_blog'), $nameImg);
            $article->setFeaturedImg($nameImg);

            $article->setCreatedAt(new \DateTime);

            $article->setUserId($this->getUser());

            $manager = $managerRegistry->getManager();
            $manager->persist($article);
            $manager->flush();
            $this->addFlash('success', 'L\'article a bien été ajoutée.');
            return $this->redirectToRoute('article_admin_index');
        }
        return $this->render('admin/adminArticleForm.html.twig', [
            'articleForm' => $form->createView()
        ]);
    }

    #[Route('/admin/article/update/{id}', name: 'article_update')]
    public function update(ArticleRepository $articleRepository, int $id, Request $request, ManagerRegistry $managerRegistry)
    {
        $article = $articleRepository->find($id);
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $slug = StripAccents::strip(str_replace([' ', '\'', '"', '&'], ['-', '-', '-', 'et'], strtolower($form['title']->getData())));
            $article->setSlug($slug);
            $artImg = $form['featured_img']->getData();
            $nameOldImg = $article->getFeaturedImg();
            if ($artImg !== null) {
                $pathOldImg = $this->getParameter('dossier_photos_blog') . '/' .
                    $nameOldImg;
                if (file_exists($pathOldImg)) {
                    unlink($pathOldImg);
                }
                $extensionImg = $artImg->guessExtension();
                $nameImg = time() . '.' . $extensionImg;
                $artImg->move($this->getParameter('dossier_photos_blog'), $nameImg);
                $article->setFeaturedImg($nameImg);
            } else {
                $article->setFeaturedImg($nameOldImg);
            }

            $article->setUpdatedAt(new \DateTime);

            $manager = $managerRegistry->getManager();
            $manager->persist($article);
            $manager->flush();
            $this->addFlash('success', 'L\'article a bien été modifiée.');
            return $this->redirectToRoute('article_admin_index');
        }

        return $this->render('admin/adminArticleForm.html.twig', [
            'articleForm' => $form->createView()
        ]);
    }

    #[Route('/admin/article/delete/{id}', name: 'article_delete')]
    public function delete(ArticleRepository $articleRepository, int $id, ManagerRegistry $managerRegistry)
    {
        $article = $articleRepository->find($id);
        $nameImg = $article->getFeaturedImg();
        if ($nameImg !== null) {
            $pathImg = $this->getParameter('dossier_photos_blog') . '/' . $nameImg;
            if (file_exists($pathImg)) {
                unlink($pathImg);
            }
        }

        $manager = $managerRegistry->getManager();
        $manager->remove($article);
        $manager->flush();
        $this->addFlash('success', 'L\'article a bien été suprimée.');
        return $this->redirectToRoute('article_admin_index');
    }
}

templates/article/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ article.title }} détails Chocoblog ♥ Les Amoureux du Chocolat ♥ {% endblock %}
{% block body %}
<div class="row border border-dark mb-6 mx-auto d-flex" id="article-infos">
    <nav aria-label="breadcrumb" id="breadcrumb">
        <ol class="breadcrumb mb-4 mt-3">
            <li class="breadcrumb-item"><a href=" {{ path('home')}} ">Accueil</a></li>
            <li class="breadcrumb-item"><a href=" {{ path('article_index')}} ">ChocoBlog article</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ article.title }}</li>
        </ol>
    </nav>
    <div class="col-md-6 ">
        <div class="product">
            <div class="item">
                <img src="{{ asset('img/Blog/' ~ article.featuredImg ) }}" alt="photo principale {{ article.title }}"
                    class="img-fluid mt-5" id="article-img">
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="product-dtl">
            <div class="product-info mt-5 text-center py-3 px-lg-5">
                <div class="row align-items-center">
                    <h4 class="article-center"> {{ article.event }} </h4>
                    <div class="text-center">
                        <h5 class="article-center">{{ article.title }}
                        </h5>
                        <p class="article-center">{{ article.content }}</p>
                    </div>
                    <div class="row mt-4">
                        <div class="col">
                            <a href=" {{ path('comment_new', {'id':article.id}) }} " class="btn article-btn"
                                id="article-btn">Commenter
                                l'article</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="pt-3 pb-3">
        <div class="container">
            <h1 class="text-center pb-4" id="article-comment-title">Découvrez ce que nos clients disent de
                l'événement
            </h1>
            {% for comment in comments|reverse %}
            {% if comment.commentStatus == true %}
            <div class="row align-items-center justify-content-center border border-dark mb-5">
                <div class="col-12 col-md-1 mt-4 mt-md-0  me-auto me-md-0 user-comment">
                    <img alt="utilisateur les amoureux du chocolat" class="img-fluid rounded-circle mb-3 mb-md-1 mt-1"
                        src=" {{ asset('img/Blog/user.png')  }} ">
                    <div class="mb-1 text-muted">
                        <em>{{comment.userId.firstName}}</em>
                    </div>
                    <p class="text-success user-comment-p">utilisateur vérifier</p>
                </div>

                <div class="col-12 col-md-7 mt-3">
                    <h4 class="comment-h4">{{ comment.title }}</h4>
                    <div class="mb-1 text-muted text-end">
                        <p class="text-muted comment-p">Posté le {{ comment.createdAt|date('d/m/y')}}
                        </p>

                    </div>
                    <p class="text-h3 pt-5 comment-content" id="comment-content">
                        {{ comment.content }}
                    </p>
                    <div class="col-12 bg-reply">
                        <p class="reply">Réponse <strong class="text-uppercase">♥ Les Amoureux du Chocolat♥</strong></p>
                        <p class="text-h3">
                            {% for reponse in reponses %}
                            {# {{ dump(reponse.fkCommentId.id) }} #}

                            {% if reponse.fkCommentId.id == comment.id %}
                            {{ reponse.answer }}
                            {% endif %}
                            {% endfor %}
                        </p>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </section>
</div>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} ChocoBlog Articles ♥ Les Amoureux du Chocolat ♥{% endblock %}

{% block body %}

<main class="container-fluid">
    {% include "shared/_flash.html.twig" %}
    <h1 class="text-center pt-5 mb-5 pb-5 title-intro-blog">ChocoBlog - Notre actualité les biens faits du chocolat
        et
        bien plus
        encore
    </h1>
    <div class="row" id="article-blog">
        {% for article in articles %}
        <div class="col-4 mt-2 pt-3 pb-5" id="article-read">
            <div class="card profile-card-blog text-center border-top-0">
                <div class="card-img-block">
                    <img src=" {{asset('img/Blog/' ~ article.featuredImg )}} " alt="photo principale {{article.title}}"
                        class="card-img-top" id="blog-img">
                </div>
                <div class="card-body pt-0">
                    <h4 class="card-title text-center mt-5"> {{ article.title}} </h4>
                    <p class="card-text"> {{ article.content|u.truncate(30, '...', false)}} </p>
                    <a href=" {{ path('article', {'id': article.id} )}} " target="_blank">Lire la
                        suite</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% endblock %}